### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by mikechristie**
Just some misc patches.

The only interesting patch may be:
"Use ceph-iscsi-config valid_disk"

This patch requires the ceph-iscsi-config addition:
https://github.com/ceph/ceph-iscsi-config/pull/76

### CODE REVIEW

**Comment by dillaman** [comment]
jenkins flake8

**Comment by mikechristie** [comment]
Patches have been rebased.

**Comment by dillaman** [comment]
@mikechristie See the flake8 errors

**Comment by mikechristie** [comment]
Ran tox locally and they are all fixed now.

I added one new patch:

https://github.com/ceph/ceph-iscsi-cli/pull/119/commits/e9f97110d9ef9df3523fa46dc2796b100c1d3a31

because for one of the ceph-iscsi-config tox changes I needed to move human_size to that package. The above patch then has us use the ceph-iscsi-config function.

**Pull request merged**
